name: Build_lambdas

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda_root: ["extract/lambda", "load/lambda", "transform/lambda"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        cd ${{matrix.lambda_root}}
        pylint '*.py'
