name: Deploy_Softwarre

on: [push]

jobs:
    build_infra:
      uses: ./.github/workflows/build_infrastructure.yml
    build_lambdas:
        uses: ./.github/workflows/build_lambdas.yaml
    deploy_to_infra:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy that bitch
              run: |
                  echo "I am deploying it now !"