name: Deploy_Software

on: 
  workflow_call:
    inputs:
      environment_name:
        type : string
        required: true
        default: 'dev'

jobs:
    build_infra:
      uses: ./.github/workflows/build_infrastructure.yml
    build_lambdas:
      uses: ./.github/workflows/build_lambdas.yml
    deploy_to_infra:
        environment : ${{inputs.environment_name}}
        needs: 
          - build_infra
          - build_lambdas
        runs-on: ubuntu-latest
        steps:
            - name: Deploy that bitch
              run: |
                  echo "I am deploying it now ! to ${{vars.MY_NAME}}"